# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d4cf6a4f5bcde4dbcfd28f637c87ba05546da00db3fd830639f1b6467f4910f78a870b62fea0158303834b1451b8aa8f9c771fd705148fc89da974843c139eb

test:
  secret_key_base: 05bff35da50b3e7d0589401905fdc3d7f7734b4a1f194f3048d50af60a483e862d1358e9d7842042729458f9aa07045bce8a8681c2526a82d3357932913267af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
